import type { Metadata } from 'next';
import './globals.css';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';
import { Container } from '../../styled-system/jsx';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Container
          height="100%"
          maxWidth="1000px"
          paddingX={{ base: '15px', desktop: 0 }}
        >
          <Header />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
