// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IAboutFields {
  /** test */
  test?: string | undefined;

  /** Site */
  site?: string | undefined;

  /** Profile */
  profile?: string | undefined;
}

/** アバウトページ */

export interface IAbout extends Entry<IAboutFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'about';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IBlogPostFields {
  /** Title */
  title: string;

  /** Slug */
  slug: string;

  /** PublishDate */
  publishDate: string;

  /** Content */
  content?: string | undefined;

  /** Category */
  category: ICategory[];
}

/** ブログの記事 */

export interface IBlogPost extends Entry<IBlogPostFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'blogPost';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ICategoryFields {
  /** Name */
  name: string;

  /** Slug */
  slug: string;
}

/** カテゴリー */

export interface ICategory extends Entry<ICategoryFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'category';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE = 'about' | 'blogPost' | 'category';

export type IEntry = IAbout | IBlogPost | ICategory;

export type LOCALE_CODE = 'ja-JP';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'ja-JP';
